"""add stopped as a task state

Revision ID: 1f30adedb41d
Revises: 9977e23f0848
Create Date: 2020-12-24 06:19:52.922667

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1f30adedb41d'
down_revision = '9977e23f0848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
