"""create task instance model

Revision ID: 39b9bff8abac
Revises: cf621ffc9e89
Create Date: 2020-12-21 06:29:45.672725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '39b9bff8abac'
down_revision = 'cf621ffc9e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('start_ts', sa.DateTime(), nullable=True),
    sa.Column('end_ts', sa.DateTime(), nullable=True),
    sa.Column('state', postgresql.ENUM('NOT_STARTED', 'STARTED', 'SCHEDULED', 'DEFERRED', 'COMPLETED', name='state', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instance')
    # ### end Alembic commands ###
