"""create task instance model

Revision ID: 9977e23f0848
Revises: 39b9bff8abac
Create Date: 2020-12-24 06:10:19.513253

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9977e23f0848'
down_revision = '39b9bff8abac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
