"""remove priority

Revision ID: a90186f5dca7
Revises: 21f46b3cc285
Create Date: 2020-12-21 03:58:51.687403

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a90186f5dca7'
down_revision = '21f46b3cc285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='priority'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
