"""add priority

Revision ID: b37b41aea793
Revises: a90186f5dca7
Create Date: 2020-12-21 03:59:06.839102

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b37b41aea793'
down_revision = 'a90186f5dca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='priority'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
