"""update task id

Revision ID: c1bc280d2aaa
Revises: 
Create Date: 2020-12-19 05:34:46.460522

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c1bc280d2aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('docker_url', sa.String(), nullable=True),
    sa.Column('command', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('NOT_STARTED', 'STARTED', 'SCHEDULED', 'DEFERRED', name='state'), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
