"""rename schedule to schedule at

Revision ID: cf621ffc9e89
Revises: b37b41aea793
Create Date: 2020-12-21 04:53:20.392544

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cf621ffc9e89'
down_revision = 'b37b41aea793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('schedule_at', sa.String(), nullable=True))
    op.drop_column('task', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'schedule_at')
    # ### end Alembic commands ###
