"""add new task state

Revision ID: f2d273743b04
Revises: c1bc280d2aaa
Create Date: 2020-12-19 13:30:17.969173

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f2d273743b04'
down_revision = 'c1bc280d2aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
