"""rename taskinstance relationship field

Revision ID: 13e145d443d8
Revises: cb038d56d9b6
Create Date: 2023-02-28 04:34:15.964549

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '13e145d443d8'
down_revision = 'cb038d56d9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
