"""add tasktype to differentiate job and cronjob

Revision ID: 1b76078a6c67
Revises: dd48573797a8
Create Date: 2023-02-28 04:29:55.624723

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1b76078a6c67'
down_revision = 'dd48573797a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_type')
    # ### end Alembic commands ###
