"""rename taskinstance relationship field

Revision ID: 8ebc8c77e968
Revises: 13e145d443d8
Create Date: 2023-02-28 04:34:58.729312

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8ebc8c77e968'
down_revision = '13e145d443d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
